#!/bin/sh
set -e

echo "Starting postinstall"

# depends
# tools
REQUIRED_TOOLS="adb fastboot xz-utils unzip zip wget curl pkexec heimdall-flash heimdall-flash-frontend coreutils xdg-desktop-portal xdg-desktop-portal-gtk xdg-utils"
# libs
REQUIRED_LIBS="libgtk-4-1 libc6 libadwaita-1"

MISSING_TOOLS=""
MISSING_LIBS=""

echo "Checking packages..."
echo "Checking tools..."
echo "$REQUIRED_TOOLS"
# check for the installed tools
for TOOL in $REQUIRED_TOOLS; do
    if ! command -v "$TOOL" >/dev/null 2>&1; then
        MISSING_TOOLS="$MISSING_TOOLS $TOOL"
    fi
done

echo "Checking libs..."
echo "REQUIRED_LIBS"
# check for the libs
for LIB in $REQUIRED_LIBS; do
    if ! dpkg -s "$LIB" >/dev/null 2>&1; then
        MISSING_LIBS="$MISSING_LIBS $LIB"
    fi
done

# install packages
if [ -n "$MISSING_TOOLS" ] || [ -n "$MISSING_LIBS" ]; then
    echo "Missing programs or libraries found: $MISSING_TOOLS $MISSING_LIBS"
    echo "Try installing packages..."

    if [ -n "$MISSING_TOOLS" ]; then
        sudo apt update && sudo apt install -y $MISSING_TOOLS
    fi

    if [ -n "$MISSING_LIBS" ]; then
        sudo apt update && sudo apt install -y $MISSING_LIBS
    fi
else
    echo "All required programs and libraries are installed."
fi

echo "Postinstall completed."

