name: fastboot-assistant
base: core24
version: '0.7.1'
summary: "Tool for installing Custom-ROMs and GSIs on Android devices"
description: |
  The Fastboot Assistant facilitates the installation of Custom-ROMs and GSIs
  on Android devices. It offers a user-friendly GTK4 interface
  and integrates tools such as adb, fastboot, and heimdall.

grade: stable
confinement: strict

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

apps:
  fastboot-assistant:
    command: usr/bin/fastboot-assistant
    plugs:
      - home
      - removable-media
      - network
      - hardware-observe
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - raw-usb
      - mount-observe
      - opengl
      - adb-support
      - gsettings
      - cups
    desktop: usr/share/applications/fastboot-assistant.desktop
    environment:
      XDG_DATA_DIRS: $SNAP/usr/share:$SNAP/share:$XDG_DATA_DIRS
      GTK_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gtk-4.0

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  gtk-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes

parts:
  fastboot-assistant:
    source: .
    plugin: dump
    organize:
      meta/gui/io.github.nachtsternbuild.Fastboot-Assistant.appdata.xml: meta/gui/io.github.nachtsternbuild.Fastboot-Assistant.appdata.xml
      fastboot-assistant.desktop: usr/share/applications/fastboot-assistant.desktop
      fastboot-assistant: usr/bin/fastboot-assistant
      sweet_unix.png: usr/share/icons/hicolor/256x256/apps/sweet_unix.png
    stage-packages:
      - adb
      - fastboot
      - xz-utils
      - unzip
      - zip
      - wget
      - curl
      - pkexec
      - heimdall-flash
      - coreutils
      - libc6
      - libgtk-4-1
      - libgtk-3-0
      - libglib2.0-0
      - dconf-gsettings-backend
      - xdg-desktop-portal
      - xdg-desktop-portal-gtk
      - xdg-utils
      - libgl1-mesa-dri
      - mesa-vulkan-drivers
      - libvulkan1
      - libdbus-glib-1-dev
      - libglib2.0-bin
      - dconf-gsettings-backend
    build-packages:
      - libglib2.0-bin
    override-build: |
      snapcraftctl build
      glib-compile-schemas $SNAPCRAFT_PART_INSTALL/usr/share/glib-2.0/schemas


slots:
  fastboot-assistant:
    interface: dbus
    bus: session
    name: io.github.nachtsternbuild.fastboot-assistant

environment:
  LIBGL_DRIVERS_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
  LIBGL_DEBUG: verbose
  MESA_LOADER_DRIVER_OVERRIDE: swrast

