.TH fastboot-assistant 1 "May 2025" "Version 0.8.1.5" "User Manual"
.SH NAME
fastboot-assistant \- assists in flashing custom ROMs on Android devices
.SH SYNOPSIS
.B fastboot-assistant
.SH DESCRIPTION
This program simplifies the installation of custom ROMs, GSIs, and firmware on Android devices.
It provides a modern GTK interface and supports tools like ADB, Fastboot, and Heimdall.
.SH AUTHOR
Elias Mörz <elias.moerz@mail.de>
.SH LICENSE
Apache License 2.0
.SH FILES
~/.config/fastboot-assistant/auto.txt
.RS
Indicates whether dark mode is enabled automatically (libadwaita).
.RE
~/.config/fastboot-assistant/dark.txt
.RS
Explicit dark mode override setting.
.RE
~/.config/fastboot-assistant/config.txt
.RS
Used for first-time setup and general configuration.
.RE
~/.config/fastboot-assistant/version.txt
.RS
Stores the current installed version.
.RE
~/.config/fastboot-assistant/path_config.txt
.RS
Specifies the path from which ROMs or firmware files are flashed.
.RE
~/.config/fastboot-assistant/log.txt
.RS
Contains logs of all actions performed by Fastboot-Assistant.
.RE

