.TH fastboot-assistant 1 "Mai 2025" "Version 0.8.1.5" "Benutzerhandbuch"
.SH NAME
fastboot-assistant \- assistiert beim Flashen von Custom-ROMs auf Android-Geräten
.SH SYNOPSIS
.B fastboot-assistant
.SH BESCHREIBUNG
Dieses Programm erleichtert die Installation von Custom-ROMs, GSIs und Firmware auf Android-Geräten.
Es bietet eine moderne GTK-Oberfläche und unterstützt Tools wie ADB, Fastboot und Heimdall.
.SH AUTOR
Elias Mörz <elias.moerz@mail.de>
.SH LIZENZ
Apache License 2.0
.SH KONFIGURATIONSDATEIEN
~/.config/fastboot-assistant/auto.txt
.RS
Gibt an, ob der Dunkelmodus automatisch aktiviert wird (libadwaita).
.RE
~/.config/fastboot-assistant/dark.txt
.RS
Explizite Einstellung für den Dunkelmodus.
.RE
~/.config/fastboot-assistant/config.txt
.RS
Dient für die Ersteinrichtung und allgemeine Konfiguration.
.RE
~/.config/fastboot-assistant/version.txt
.RS
Speichert die aktuell installierte Version.
.RE
~/.config/fastboot-assistant/path_config.txt
.RS
Legt den Pfad fest, von dem ROMs oder Firmware-Dateien geflasht werden.
.RE
~/.config/fastboot-assistant/log.txt
.RS
Enthält alle Protokolleinträge des Fastboot-Assistants.
.RE

