name: fastboot-assistant
base: core24
version: '0.9.1'
summary: "Tool for installing Custom-ROMs and GSIs on Android devices"
description: |
  The Fastboot Assistant facilitates the installation of Custom-ROMs and GSIs
  on Android devices. It offers a user-friendly GTK4/Libadwaita interface
  and integrates tools such as adb, fastboot, and heimdall.

title: Fastboot-Assistant
contact: elias.moerz@mail.de
license: GPL-3.0
donation: https://github.com/NachtsternBuild/fastboot-assistant
issues: https://github.com/NachtsternBuild/fastboot-assistant/issues
source-code: https://github.com/NachtsternBuild/fastboot-assistant
website: https://nachtsternbuild.github.io/fastboot-assistant/

grade: stable
confinement: strict

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

apps:
  fastboot-assistant:
    command: usr/bin/fastboot-assistant
    desktop: usr/share/applications/fastboot-assistant.desktop
    extensions: [gnome]
    plugs:
      - home
      - removable-media
      - network
      - hardware-observe
      - raw-usb
      - mount-observe
      - opengl
      - adb-support
      - gsettings
      - system-observe
      - process-control
      - wayland
      - x11
      - uhid
      - cups
    environment:
      GI_TYPELIB_PATH: "$SNAP/usr/lib/girepository-1.0:$GI_TYPELIB_PATH"
      GSETTINGS_SCHEMA_DIR: "$SNAP/usr/share/glib-2.0/schemas"

slots:
  fastboot-assistant:
    interface: dbus
    bus: session
    name: io.github.nachtsternbuild.Fastboot-Assistant

parts:
  adb-fastboot:
    plugin: nil
    source: https://dl.google.com/android/repository/platform-tools-latest-linux.zip
    override-build: |
      set -xe
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      curl -L -o platform-tools.zip https://dl.google.com/android/repository/platform-tools-latest-linux.zip
      unzip -o platform-tools.zip
      mv platform-tools/* $SNAPCRAFT_PART_INSTALL/usr/bin/
      chmod +x $SNAPCRAFT_PART_INSTALL/usr/bin/adb
      chmod +x $SNAPCRAFT_PART_INSTALL/usr/bin/fastboot
    build-packages:
      - unzip
      - curl
    stage-packages:
      - libusb-1.0-0

  heimdall:
    plugin: nil
    source: https://github.com/Benjamin-Dobell/Heimdall/archive/refs/tags/v1.4.2.zip
    override-build: |
      set -xe
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      curl -L -o heimdall.zip https://github.com/Benjamin-Dobell/Heimdall/archive/refs/tags/v1.4.2.zip
      unzip -o heimdall.zip
      cd Heimdall-1.4.2
      mkdir build && cd build
      cmake ..
      make -j$(nproc)
      cp bin/heimdall $SNAPCRAFT_PART_INSTALL/usr/bin/
      chmod +x $SNAPCRAFT_PART_INSTALL/usr/bin/heimdall
    build-packages:
      - cmake
      - build-essential
      - libusb-1.0-0-dev
      - qtbase5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - qtchooser
      - qt5-qmake
    stage-packages:
      - libusb-1.0-0
      - libqt5widgets5
      - qt5-qmake
      - libqt5gui5
      - libqt5core5a

  fastboot-assistant:
    source: https://github.com/NachtsternBuild/fastboot-assistant.git
    source-type: git
    plugin: make
    build-packages:
      - debhelper-compat
      - rsync
      - libgtk-4-dev
      - libadwaita-1-dev
      - libsecret-1-dev
      - pkgconf
      - gcc
      - make
      - libvte-2.91-gtk4-dev
      - libglib2.0-dev
      - git
      - libglib2.0-dev
      - libnotify-dev
      - ccache
    build-snaps:
      - gnome-46-2404-sdk/latest/candidate
    stage-packages:
      - libvte-2.91-gtk4-0
      - gir1.2-vte-2.91
      - libproxy1-plugin-gsettings
      - libproxy1-plugin-networkmanager
      - libproxy1v5

    override-build: |
      set -eux
      cd src
      make -f Dependencies.mk GIT_HTTPS=1
      make GIT_HTTPS=1
      install -Dm755 fastboot-assistant $SNAPCRAFT_PART_INSTALL/usr/bin/fastboot-assistant
      install -Dm644 assets/sweet_unix.png $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps/sweet_unix.png
      install -Dm644 assets/fastboot-assistant-snap.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications/fastboot-assistant.desktop
      glib-compile-schemas $SNAPCRAFT_PART_INSTALL/usr/share/glib-2.0/schemas
      gio-querymodules $SNAPCRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gio/modules
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/girepository-1.0
      VTE_TLIB=$(find $SNAPCRAFT_PART_INSTALL -name "Vte-2.91.typelib" | head -n1)
      cp "$VTE_TLIB" $SNAPCRAFT_PART_INSTALL/usr/lib/girepository-1.0/
