name: fastboot-assistant
base: core24
version: '0.9.1'
summary: "Tool for installing Custom-ROMs and GSIs on Android devices"
description: |
  The Fastboot Assistant facilitates the installation of Custom-ROMs and GSIs
  on Android devices. It offers a user-friendly GTK4/Libadwaita interface
  and integrates tools such as adb, fastboot, and heimdall.
  
# required for metadata
title: Fastboot-Assistant
contact: elias.moerz@mail.de
license: GPL-3.0

# required by lint
donation: https://github.com/NachtsternBuild/fastboot-assistant
issues: https://github.com/NachtsternBuild/fastboot-assistant/issues
source-code: https://github.com/NachtsternBuild/fastboot-assistant
website: https://nachtsternbuild.github.io/fastboot-assistant/


grade: stable
confinement: strict

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.0:
    bind: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.0
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.1
  /usr/share/xml/iso-codes:
    bind: $SNAP/gnome-platform/usr/share/xml/iso-codes
  /usr/share/libdrm:
    bind: $SNAP/gpu-2404/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/gpu-2404/drirc.d
  /usr/share/X11/XErrorDB:
    symlink: $SNAP/gpu-2404/X11/XErrorDB
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gio/modules:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gio/modules

apps:
  fastboot-assistant:
    command: usr/bin/fastboot-assistant
    desktop: usr/share/applications/fastboot-assistant.desktop
    extensions: [gnome]
    plugs:
      - home
      - removable-media
      - network
      - hardware-observe
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - raw-usb
      - mount-observe
      - opengl
      - adb-support
      - gsettings
      - cups
      - uhid
      - gnome
      - system-observe
    slots:
      - fastboot-assistant
    environment:
      XDG_DATA_DIRS: $SNAP/usr/share:$SNAP/share:$XDG_DATA_DIRS
      GTK_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gtk-4.0
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
      GI_TYPELIB_PATH: $SNAP/usr/lib/girepository-1.0:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/girepository-1.0:$GI_TYPELIB_PATH
      GIO_EXTRA_MODULES: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gio/modules
      GTK_USE_PORTAL: "1"
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH"
      GTK_MEDIA_BACKEND: "none"
      LIBPROXY_PLUGIN_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libproxy


plugs:    
  dbus:
    interface: dbus
    bus: session
    name: org.freedesktop.portal.Desktop
  opengl:
    interface: opengl  
  desktop:
    mount-host-font-cache: false
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  gnome:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-46-2404
  gnome-46-2404:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-46-2404
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404  
    
slots:
  fastboot-assistant:
    interface: dbus
    bus: session
    name: io.github.nachtsternbuild.Fastboot-Assistant

environment:
  LIBGL_DRIVERS_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
  LIBGL_DEBUG: verbose
  MESA_LOADER_DRIVER_OVERRIDE: swrast
  SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform
  GTK_USE_PORTAL: "1"
  LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH"
  GIO_EXTRA_MODULES: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gio/modules
  

parts:
  adb-fastboot:
    plugin: nil
    source: https://dl.google.com/android/repository/platform-tools-latest-linux.zip
    override-build: |
      set -xe
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      curl -L -o platform-tools.zip https://dl.google.com/android/repository/platform-tools-latest-linux.zip
      unzip -o platform-tools.zip
      mv platform-tools/* $SNAPCRAFT_PART_INSTALL/usr/bin/
      chmod +x $SNAPCRAFT_PART_INSTALL/usr/bin/adb
      chmod +x $SNAPCRAFT_PART_INSTALL/usr/bin/fastboot
    build-packages:
      - unzip
      - curl
    stage-packages:
      - libusb-1.0-0

  heimdall:
    plugin: nil
    source: https://github.com/Benjamin-Dobell/Heimdall/archive/refs/tags/v1.4.2.zip
    override-build: |
      set -xe
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      curl -L -o heimdall.zip https://github.com/Benjamin-Dobell/Heimdall/archive/refs/tags/v1.4.2.zip
      unzip -o heimdall.zip
      cd Heimdall-1.4.2
      mkdir build && cd build
      cmake ..
      make -j$(nproc)
      cp bin/heimdall $SNAPCRAFT_PART_INSTALL/usr/bin/
      chmod +x $SNAPCRAFT_PART_INSTALL/usr/bin/heimdall
    build-packages:
      - cmake
      - build-essential
      - libusb-1.0-0-dev
      - qtbase5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - qtchooser
      - qt5-qmake
    stage-packages:
      - libusb-1.0-0
      - libqt5widgets5
      - qt5-qmake
      - libqt5gui5
      - libqt5core5a

  fastboot-assistant:
    source: https://github.com/NachtsternBuild/fastboot-assistant.git
    source-type: git
    plugin: make
    organize:
      fastboot-assistant: $SNAPCRAFT_PART_INSTALL/usr/bin/fastboot-assistant
      assets/fastboot-assistant-snap.desktop: $SNAPCRAFT_PART_INSTALL/usr/share/applications/fastboot-assistant.desktop
      assets/sweet_unix.png: $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps/sweet_unix.png
    build-packages:
      - debhelper-compat
      - rsync
      - libgtk-4-dev
      - libadwaita-1-dev
      - libsecret-1-dev
      - pkgconf
      - gcc
      - make
      - libvte-2.91-gtk4-dev
      - libglib2.0-dev
      - git
      - libglib2.0-dev
      - libnotify-dev
      - ccache
    build-snaps:
      - gnome-46-2404-sdk/latest/candidate
    stage-packages:
      - xz-utils
      - unzip
      - zip
      - wget
      - curl
      - pkexec
      - xdg-desktop-portal
      - xdg-desktop-portal-gtk
      - xdg-utils
      - libvulkan1
      - libproxy1v5
      - libproxy1-plugin-gsettings
      - libproxy1-plugin-networkmanager
      - libnotify-bin
    override-build: |
      set -eux
      cd src
      make -f Dependencies.mk GIT_HTTPS=1
      make GIT_HTTPS=1
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin/
      cp fastboot-assistant $SNAPCRAFT_PART_INSTALL/usr/bin/
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications/
      cp assets/fastboot-assistant-snap.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications/fastboot-assistant.desktop
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps/
      cp assets/sweet_unix.png $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps/sweet_unix.png 
      glib-compile-schemas $SNAPCRAFT_PART_INSTALL/usr/share/glib-2.0/schemas
      gio-querymodules $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/gio/modules     
    build-environment:
      - PATH: /snap/gnome-46-2404-sdk/current/usr/bin${PATH:+:$PATH}
      - XDG_DATA_DIRS: $CRAFT_STAGE/usr/share:/snap/gnome-46-2404-sdk/current/usr/share:/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
      - LD_LIBRARY_PATH: /snap/gnome-46-2404-sdk/current/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/gnome-46-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/gnome-46-2404-sdk/current/usr/lib:/snap/gnome-46-2404-sdk/current/usr/lib/vala-current:/snap/gnome-46-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
      - PKG_CONFIG_PATH: /snap/gnome-46-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig:/snap/gnome-46-2404-sdk/current/usr/lib/pkgconfig:/snap/gnome-46-2404-sdk/current/usr/share/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
      - GETTEXTDATADIRS: /snap/gnome-46-2404-sdk/current/usr/share/gettext-current${GETTEXTDATADIRS:+:$GETTEXTDATADIRS}
      - GDK_PIXBUF_MODULE_FILE: /snap/gnome-46-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-current/loaders.cache
      - ACLOCAL_PATH: /snap/gnome-46-2404-sdk/current/usr/share/aclocal${ACLOCAL_PATH:+:$ACLOCAL_PATH}
      - PYTHONPATH: /snap/gnome-46-2404-sdk/current/usr/lib/python3.10:/snap/gnome-46-2404-sdk/current/usr/lib/python3/dist-packages:/snap/gnome-46-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gobject-introspection${PYTHONPATH:+:$PYTHONPATH}
      - GI_TYPELIB_PATH: /snap/gnome-46-2404-sdk/current/usr/lib/girepository-1.0:/snap/gnome-46-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0${GI_TYPELIB_PATH:+:$GI_TYPELIB_PATH}
